name: Daily GitHub Trending Collector

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 의존성 설치
        run: pip install requests beautifulsoup4

      - name: 트렌딩 수집 실행
        run: python trending_repo.py

      - name: README 업데이트
        run: python update_readme.py

      - name: 커밋 및 푸시
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md *.txt
          git commit -m "자동 수집 결과 반영"
          git push
